# Generated by Django 5.2.16 on 2026-07-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cedula",
                    models.CharField(
                        help_text="Número de documento de identidad único del paciente",
                        max_length=20,
                        unique=True,
                        verbose_name="Cédula de Identidad",
                    ),
                ),
                ("nombres", models.CharField(max_length=100, verbose_name="Nombres")),
                (
                    "apellidos",
                    models.CharField(max_length=100, verbose_name="Apellidos"),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(verbose_name="Fecha de Nacimiento"),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("F", "Femenino"), ("M", "Masculino"), ("O", "Otro")],
                        max_length=1,
                        verbose_name="Sexo Biológico",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(max_length=20, verbose_name="Teléfono Principal"),
                ),
                ("direccion", models.TextField(verbose_name="Dirección de Habitación")),
                (
                    "correo_electronico",
                    models.EmailField(
                        blank=True,
                        help_text="Campo opcional",
                        max_length=254,
                        null=True,
                        verbose_name="Correo Electrónico",
                    ),
                ),
                (
                    "contacto_emergencia_nombre",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Nombre de Contacto de Emergencia",
                    ),
                ),
                (
                    "contacto_emergencia_telefono",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Teléfono de Contacto de Emergencia",
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro en Sistema"
                    ),
                ),
            ],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
                "ordering": ["apellidos", "nombres"],
            },
        ),
    ]
