# Generated by Django 5.2.16 on 2026-07-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="activo",
            field=models.BooleanField(
                default=True,
                help_text="Define si el paciente está habilitado o deshabilitado (borrado lógico)",
                verbose_name="Paciente Activo",
            ),
        ),
    ]
