# Generated by Django 5.2.16 on 2026-07-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_hora",
                    models.DateTimeField(verbose_name="Fecha y Hora de la Cita"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("ATENDIDA", "Atendida"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado de la Cita",
                    ),
                ),
                (
                    "motivo",
                    models.CharField(max_length=255, verbose_name="Motivo de la Cita"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Agendamiento"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cita Médica",
                "verbose_name_plural": "Citas Médicas",
                "ordering": ["-fecha_hora"],
            },
        ),
    ]
