# Generated by Django 5.2.16 on 2026-07-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistorialClinico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_consulta",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y Hora de Consulta"
                    ),
                ),
                (
                    "motivo_consulta",
                    models.TextField(verbose_name="Motivo de Consulta"),
                ),
                (
                    "antecedentes",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Antecedentes Médicos / Personales",
                    ),
                ),
                ("diagnostico", models.TextField(verbose_name="Diagnóstico")),
                (
                    "notas_observaciones",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Notas u Observaciones Adicionales",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial Clínico",
                "verbose_name_plural": "Historiales Clínicos",
                "ordering": ["-fecha_consulta"],
            },
        ),
        migrations.CreateModel(
            name="Receta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_emision",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Emisión"
                    ),
                ),
                (
                    "indicaciones_medicamentos",
                    models.TextField(
                        verbose_name="Indicaciones y Medicamentos Recetados"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones Adicionales"
                    ),
                ),
            ],
            options={
                "verbose_name": "Receta Médica",
                "verbose_name_plural": "Recetas Médicas",
                "ordering": ["-fecha_emision"],
            },
        ),
    ]
