# Generated by Django 5.2.16 on 2026-07-21 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("historias", "0001_initial"),
        ("pacientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historialclinico",
            name="medico",
            field=models.ForeignKey(
                limit_choices_to={"rol": "MEDICO"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consultas_realizadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Médico Tratante",
            ),
        ),
        migrations.AddField(
            model_name="historialclinico",
            name="paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historias_clinicas",
                to="pacientes.paciente",
                verbose_name="Paciente",
            ),
        ),
        migrations.AddField(
            model_name="receta",
            name="historial_clinico",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receta",
                to="historias.historialclinico",
                verbose_name="Consulta / Historial Clínico Asociado",
            ),
        ),
    ]
