# Generated by Django 5.2.16 on 2026-07-22 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("CREAR", "Crear"),
                            ("EDITAR", "Editar"),
                            ("ELIMINAR", "Eliminar"),
                            ("DESACTIVAR", "Desactivar"),
                            ("LOGIN", "Iniciar Sesión"),
                            ("LOGOUT", "Cerrar Sesión"),
                        ],
                        max_length=20,
                        verbose_name="Acción ejecutada",
                    ),
                ),
                (
                    "modelo_afectado",
                    models.CharField(
                        help_text="Nombre de la entidad involucrada (ej: Paciente, Cita, Consulta)",
                        max_length=100,
                        verbose_name="Módulo / Tabla afectada",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Detalle legible de los cambios o acción realizada",
                        verbose_name="Descripción de la actividad",
                    ),
                ),
                (
                    "fecha_hora",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y hora del suceso"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que ejecutó la acción. Nulo si el usuario fue eliminado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Actividad",
                "verbose_name_plural": "Registros de Actividades",
                "ordering": ["-fecha_hora"],
            },
        ),
    ]
